### ISSUE TITLE
Kodi Library integration crashing

### ISSUE THREAD

**Issue by fidelix** [anxdpanic/plugin.video.composite_for_plex#202]
### Context

* Add-on Version:
* Kodi Version: 19 (also happened with Kodi 18)
* Kodi GUI Language: English
* Operating System: Android
* Operating System Language: English

------

### Current Behavior

Error message and then nothing happens.

Exception:
```
2021-02-21 13:00:01.815 T:29158   DEBUG <general>: GetLanguageInvoker - Reusing LanguageInvokerThread 8 for script /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/entry_point.py
2021-02-21 13:00:01.815 T:32453    INFO <general>: initializing python engine.
2021-02-21 13:00:01.816 T:32453   DEBUG <general>: CPythonInvoker(8, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/entry_point.py): start processing
2021-02-21 13:00:01.816 T:32453   DEBUG <general>: CPythonInvoker(8, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/entry_point.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib
2021-02-21 13:00:01.816 T:32453   DEBUG <general>: CPythonInvoker(8, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/entry_point.py): instantiating addon using automatically obtained id of "plugin.video.composite_for_plex" dependent on version 3.0.0 of the xbmc.python api
2021-02-21 13:00:01.817 T:32453   DEBUG <general>: Composite.settings -> Reading settings configuration
2021-02-21 13:00:01.826 T:32453   DEBUG <general>: Composite -> get_params : Parameters || -> |{'url': None, 'command': 'select_library_sections', 'path_mode': None}|
2021-02-21 13:00:01.827 T:32453    INFO <general>: Composite -> _start : Composite 1.4.1+matrix.1: Kodi 19 on Linux with Python 3.8.5.final.0
2021-02-21 13:00:01.828 T:32453    INFO <general>: Composite -> _start : Mode |-1| Command |select_library_sections| Url |None| Parameters |{'url': None, 'command': 'select_library_sections', 'path_mode': None}| Server UUID |None| Media Id |None|
2021-02-21 13:00:01.831 T:32453   DEBUG <general>: Composite.settings -> Reading settings configuration
2021-02-21 13:00:01.841 T:32453   DEBUG <general>: Composite.cachecontrol -> __init__ : Running with cache location: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.composite_for_plex/cache/servers/
2021-02-21 13:00:01.842 T:32453   DEBUG <general>: Composite.cachecontrol -> read_cache : CACHE [plexhome_user.pcache]: attempting to read
2021-02-21 13:00:01.844 T:32453   DEBUG <general>: Composite.cachecontrol -> read_cache : CACHE [plexhome_user.pcache]: read
2021-02-21 13:00:01.845 T:32453   DEBUG <general>: Composite.plex -> load_tokencache : plexhome_cache data loaded successfully
2021-02-21 13:00:01.846 T:32453   DEBUG <general>: Composite.plex -> setup_user_token : myPlex is logged in
2021-02-21 13:00:01.846 T:32453   DEBUG <general>: Composite.plex -> setup_user_token : Plexhome is enabled
2021-02-21 13:00:01.848 T:32453   DEBUG <general>: Composite.plex -> setup_user_token : No user set.  Will default to admin user
2021-02-21 13:00:01.849 T:32453   DEBUG <general>: Composite.cachecontrol -> write_cache : CACHE [plexhome_user.pcache]: Writing file
2021-02-21 13:00:01.852 T:32453   DEBUG <general>: Composite.plex -> setup_user_token : myPlex user id: 393381d97e6fabff90f579d06cb2be90
2021-02-21 13:00:01.853 T:32453   DEBUG <general>: Composite.plex -> setup_user_token : Effective user id: 393381d97e6fabff90f579d06cb2be90
2021-02-21 13:00:01.854 T:32453   DEBUG <general>: Composite.plex -> load : Loading cached server list
2021-02-21 13:00:01.856 T:32453   DEBUG <general>: Composite.cachecontrol -> is_valid : CACHE [discovered_plex_servers.cache]: exists, ttl: |3600|
2021-02-21 13:00:01.858 T:32453   DEBUG <general>: Composite.cachecontrol -> is_valid : CACHE [discovered_plex_servers.cache]: mod[1613912179] now[1613912402] diff[223]
2021-02-21 13:00:01.859 T:32453   DEBUG <general>: Composite.cachecontrol -> check_cache : CACHE [discovered_plex_servers.cache]: current
2021-02-21 13:00:01.860 T:32453   DEBUG <general>: Composite.cachecontrol -> read_cache : CACHE [discovered_plex_servers.cache]: attempting to read
2021-02-21 13:00:01.861 T:32453   DEBUG <general>: Composite.cachecontrol -> read_cache : CACHE [discovered_plex_servers.cache]: read
2021-02-21 13:00:01.862 T:32453   DEBUG <general>: Composite.plex -> load : Server list is now: {'8487a6355605f52274757a6dad6dad2807a21116': <composite_addon.plex.plexserver.PlexMediaServer object at 0x2dc964a490>, 'c70e3aa312c3790fcd8b636bbc4cc96655d1fcc6': <composite_addon.plex.plexserver.PlexMediaServer object at 0x2dc964a4f0>}
2021-02-21 13:00:01.864 T:32453   DEBUG <general>: Composite.plex -> talk_to_myplex : url = https://plex.tv/pms/system/library/sections
2021-02-21 13:00:02.047 T:32453   DEBUG <general>: Composite -> run : Using list of 11 sections: [<composite_addon.plex.plexsection.PlexSection object at 0x2dc964b000>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc964afd0>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc964afa0>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc964af70>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc91204a0>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc964a070>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc964a5b0>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc964a5e0>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc964a610>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc964a640>, <composite_addon.plex.plexsection.PlexSection object at 0x2dc964a6d0>]
2021-02-21 13:00:02.054 T:32453   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'abf502c8f2b06c672eaa0738fcc2cb1374961635'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/entry_point.py", line 18, in <module>
                                                       composite.run(time.time())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/composite_addon/composite.py", line 163, in run
                                                       configure_library_sections.run(context, reset=False)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/composite_addon/routes/configure_library_sections.py", line 38, in run
                                                       movie_sections, tvshow_sections = get_sections(context, all_sections, use_details)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/composite_addon/routes/configure_library_sections.py", line 87, in get_sections
                                                       server = context.plex_network.get_server_from_uuid(server_uuid)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/composite_addon/plex/plex.py", line 707, in get_server_from_uuid
                                                       return self.server_list[_uuid]
                                                   KeyError: 'abf502c8f2b06c672eaa0738fcc2cb1374961635'
                                                   -->End of Python script error report<--
                                                   
2021-02-21 13:00:02.054 T:32453   DEBUG <general>: onExecutionDone(8, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/entry_point.py)
2021-02-21 13:00:02.065 T:29158   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-02-21 13:00:02.133 T:32453   DEBUG <general>: .
2021-02-21 13:00:02.317 T:32453    INFO <general>: Python interpreter stopped
2021-02-21 13:00:02.318 T:32453   DEBUG <general>: Skipped 10 duplicate messages..
2021-02-21 13:00:02.318 T:32453   DEBUG <general>: Thread LanguageInvoker 196543653104 terminating
2021-02-21 13:00:06.888 T:32368   DEBUG <general>: Thread JobWorker 196537009392 terminating (autodelete)
2021-02-21 13:00:06.913 T:32370   DEBUG <general>: Thread JobWorker 196542612720 terminating (autodelete)
2021-02-21 13:00:07.895 T:29158   DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------
```

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by Drakonas** [comment]
I have the same issue. On the latest app for Shield TV. Composite 1.4.2+matrix.1: Kodi 19 on Linux with Python 3.8.5.final.0.

`2022-02-21 18:33:50.560 T:15688    INFO <general>: initializing python engine.
2022-02-21 18:33:50.570 T:15688    INFO <general>: Composite -> _start : Composite 1.4.2+matrix.1: Kodi 19 on Linux with Python 3.8.5.final.0
2022-02-21 18:33:50.571 T:15688    INFO <general>: Composite -> _start : Mode |-1| Command |select_library_sections| Url |None| Parameters |{'url': None, 'command': 'select_library_sections', 'path_mode': None}| Server UUID |None| Media Id |None|
2022-02-21 18:33:51.505 T:15688   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'e9d159c85c63a5f52d971beecd6b57c71820fdeb'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/entry_point.py", line 18, in <module>
                                                       composite.run(time.time())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/composite_addon/composite.py", line 168, in run
                                                       configure_library_sections.run(context, reset=False)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/composite_addon/routes/configure_library_sections.py", line 38, in run
                                                       movie_sections, tvshow_sections = get_sections(context, all_sections, use_details)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/composite_addon/routes/configure_library_sections.py", line 87, in get_sections
                                                       server = context.plex_network.get_server_from_uuid(server_uuid)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.composite_for_plex/resources/lib/composite_addon/plex/plex.py", line 704, in get_server_from_uuid
                                                       return self.server_list[_uuid]
                                                   KeyError: 'e9d159c85c63a5f52d971beecd6b57c71820fdeb'
                                                   -->End of Python script error report<--
                                                   
2022-02-21 18:33:52.404 T:15688    INFO <general>: Python interpreter stopped
2022-02-21 18:34:08.362 T:12908    INFO <general>: Skipped 4 duplicate messages..
2022-02-21 18:34:08.362 T:12908    INFO <general>: CWinSystemAndroid::DestroyWindow
`

**Comment by anxdpanic** [comment]
Can you please try: http://ftp.fau.de/osmc/osmc/download/dev/anxdpanic/kodi/composite/python3/zips/plugin.video.composite_for_plex/plugin.video.composite_for_plex-1.4.1+matrix.1.zip and provide a debug log if it's still an issue

**Comment by chiggerz** [comment]
anyone get any further with this? I am getting same issue and log looks exactly like the above posted.... Kodi 19.  Movies scans perfect, but TV shows just can't get it working, although can see the libraries and view from composite add-on itself

**Comment by Serph91P** [comment]
> Can you please try: http://ftp.fau.de/osmc/osmc/download/dev/anxdpanic/kodi/composite/python3/zips/plugin.video.composite_for_plex/plugin.video.composite_for_plex-1.4.1

+matrix.1.zip and provide a debug log if it's still an issue

@anxdpanic I guess I have something similar but it crashes after the scan is started:
````
2023-06-12 19:34:41.563 T:20312   debug <general>: Composite.settings -> Reading settings configuration
2023-06-12 19:34:41.567 T:20312   debug <general>: Composite.cachecontrol -> is_valid : CACHE [a54117d62b7b5af07343869ca2015dbf2e94b3b647ef7085f91b09a416ec08dc88305e0dc3a716d681cd301ac1b5403850151fefc141bb589e207d802d6f7eac.cache]: exists, ttl: |900|
2023-06-12 19:34:41.567 T:20312   debug <general>: Composite.cachecontrol -> is_valid : CACHE [a54117d62b7b5af07343869ca2015dbf2e94b3b647ef7085f91b09a416ec08dc88305e0dc3a716d681cd301ac1b5403850151fefc141bb589e207d802d6f7eac.cache]: mod[1686590961] now[1686591282] diff[321]
2023-06-12 19:34:41.567 T:20312   debug <general>: Composite.cachecontrol -> check_cache : CACHE [a54117d62b7b5af07343869ca2015dbf2e94b3b647ef7085f91b09a416ec08dc88305e0dc3a716d681cd301ac1b5403850151fefc141bb589e207d802d6f7eac.cache]: current
2023-06-12 19:34:41.568 T:20312   debug <general>: Composite.cachecontrol -> read_cache : CACHE [a54117d62b7b5af07343869ca2015dbf2e94b3b647ef7085f91b09a416ec08dc88305e0dc3a716d681cd301ac1b5403850151fefc141bb589e207d802d6f7eac.cache]: attempting to read
2023-06-12 19:34:41.568 T:20312   debug <general>: Composite.cachecontrol -> read_cache : CACHE [a54117d62b7b5af07343869ca2015dbf2e94b3b647ef7085f91b09a416ec08dc88305e0dc3a716d681cd301ac1b5403850151fefc141bb589e207d802d6f7eac.cache]: read
2023-06-12 19:34:41.568 T:20312   debug <general>: Composite.plexserver -> get_sections : Returning sections: [<composite_addon.plex.plexsection.PlexSection object at 0x7f71b6e6b250>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6e6a650>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6823fd0>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6823a50>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6820e10>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6820350>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6821690>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6821d10>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6823bd0>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6e6aa50>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6823a10>]
2023-06-12 19:34:41.568 T:20312   debug <general>: Composite.settings -> Reading settings configuration
2023-06-12 19:34:41.572 T:20312   debug <general>: Composite.cachecontrol -> is_valid : CACHE [77736932c363139e3054d1256e2cecac67eda45ae21024b46ea4a676223ad03527b7b345d06bc2837fa1c4bba0a423e2e96fadaa184f946f9629d75e99656101.cache]: exists, ttl: |900|
2023-06-12 19:34:41.572 T:20312   debug <general>: Composite.cachecontrol -> is_valid : CACHE [77736932c363139e3054d1256e2cecac67eda45ae21024b46ea4a676223ad03527b7b345d06bc2837fa1c4bba0a423e2e96fadaa184f946f9629d75e99656101.cache]: mod[1686590961] now[1686591282] diff[321]
2023-06-12 19:34:41.572 T:20312   debug <general>: Composite.cachecontrol -> check_cache : CACHE [77736932c363139e3054d1256e2cecac67eda45ae21024b46ea4a676223ad03527b7b345d06bc2837fa1c4bba0a423e2e96fadaa184f946f9629d75e99656101.cache]: current
2023-06-12 19:34:41.572 T:20312   debug <general>: Composite.cachecontrol -> read_cache : CACHE [77736932c363139e3054d1256e2cecac67eda45ae21024b46ea4a676223ad03527b7b345d06bc2837fa1c4bba0a423e2e96fadaa184f946f9629d75e99656101.cache]: attempting to read
2023-06-12 19:34:41.573 T:20312   debug <general>: Composite.cachecontrol -> read_cache : CACHE [77736932c363139e3054d1256e2cecac67eda45ae21024b46ea4a676223ad03527b7b345d06bc2837fa1c4bba0a423e2e96fadaa184f946f9629d75e99656101.cache]: read
2023-06-12 19:34:41.573 T:20312   debug <general>: Composite.plexserver -> get_sections : Returning sections: [<composite_addon.plex.plexsection.PlexSection object at 0x7f71b6e7a190>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71cc823410>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71cc8213d0>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6839d90>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6839fd0>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6838710>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6838510>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6838350>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b683aa90>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6e7a790>, <composite_addon.plex.plexsection.PlexSection object at 0x7f71b6838650>]
2023-06-12 19:34:41.573 T:20312    info <general>: Composite -> _finished : Finished. |1.201s|
2023-06-12 19:34:41.574 T:20312   debug <general>: CPythonInvoker(2, /home/maxe/.kodi/addons/plugin.video.composite_for_plex/resources/lib/entry_point.py): script successfully run
2023-06-12 19:34:41.590 T:20326   debug <general>: VideoInfoScanner: Scanning dir 'plugin://plugin.video.composite_for_plex/library/movies/' as not in the database
2023-06-12 19:34:41.590 T:20327   debug <general>: Thread JobWorker start, auto delete: true
2023-06-12 19:34:41.590 T:20327   debug <general>: easy_acquire - Created session to https://readacted.57d7a027febb451395a15829bb881bd4.plex.direct
``````
